name: Go API CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build Go application
        run: go build -v ./api/main.go
      
      - name: Configure Docker for insecure registry
        run: |
          # Create a new daemon.json file
          echo '{
            "insecure-registries": ["registry.tools.svc.cluster.local:5000"]
          }' | sudo tee /etc/docker/daemon.json
          
          # Try to reload Docker configuration without restarting
          sudo kill -SIGHUP $(pidof dockerd) || echo "Could not send SIGHUP to dockerd"
          
          # Wait for configuration to apply
          sleep 5
          
          # Verify configuration
          docker info | grep -A 5 "Insecure Registries"
      
      - name: Build Docker Image
        run: |
          docker build -t registry.tools.svc.cluster.local:5000/erp-api:${{ github.sha }} -t registry.tools.svc.cluster.local:5000/erp-api:latest .
      
      - name: Login to Docker Registry
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login registry.tools.svc.cluster.local:5000 --username "${{ secrets.DOCKER_USERNAME }}" --password-stdin
      
      - name: Push Docker Image
        run: |
          # First attempt with native Docker push
          docker push registry.tools.svc.cluster.local:5000/erp-api:${{ github.sha }} || echo "Native push failed"
          docker push registry.tools.svc.cluster.local:5000/erp-api:latest || echo "Native push failed"
            
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"
      
      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment/erp-api -n tools
      
      - name: Validate Kubernetes deployment
        run: kubectl rollout status deployment/erp-api -n tools