name: Go API CI/CD

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.24"
          cache: true

      - name: Install dependencies
        run: go mod download

      - name: Build
        run: go build -v ./api/main.go

      - name: Configure Docker for insecure registry
        run: |
          # Configure Docker to work with insecure registry
          echo '{
            "insecure-registries" : ["registry.tools.svc.cluster.local:5000"]
          }' | sudo tee /etc/docker/daemon.json

          # Restart Docker to apply changes
          sudo systemctl restart docker || sudo service docker restart || true
          sleep 5

          # Verify Docker is working
          docker info

      - name: Build and Push Docker image
        env:
          REGISTRY: registry.tools.svc.cluster.local:5000
          IMAGE_NAME: erp-api
        run: |
          TIMESTAMP=$(date +%Y%m%d%H%M%S)
          TAG=${GITHUB_SHA::7}
          
          # Build the image
          docker build -t ${REGISTRY}/${IMAGE_NAME}:${TIMESTAMP}-${TAG} -t ${REGISTRY}/${IMAGE_NAME}:latest .
          
          # Force HTTP protocol version for push
          export DOCKER_CLI_EXPERIMENTAL=enabled
          docker push --tls-verify=false ${REGISTRY}/${IMAGE_NAME}:${TIMESTAMP}-${TAG}
          docker push --tls-verify=false ${REGISTRY}/${IMAGE_NAME}:latest

      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: "latest"
          
      - name: Restart Kubernetes deployment
        run: kubectl rollout restart deployment/erp-api -n tools

      # Uncomment the following for rollout status verification
      # - name: Verify Kubernetes deployment
      #   run: kubectl rollout status deployment/erp-api -n tools