name: Go API CI/CD

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: self-hosted
    # This targets your specific runner
    # You can also use a label if you've configured one: runs-on: [self-hosted, erp-runner]
    
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.24'
        cache: true

    - name: Install dependencies
      run: go mod download

    - name: Build
      run: go build -v ./api/main.go

    - name: Test
      run: go test -v ./...
      
    # Add deployment steps if needed
    # - name: Deploy
    #   run: |
    #     # Your deployment commands here